- name: install docker dependencies
  apt:
    name: [apt-transport-https, ca-certificates, curl, gnupg-agent, software-properties-common]
    state: present
    update_cache: yes
- name: add docker registory key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
- name: add docker repository source
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: no
    filename: docker
- name: add nvidia-docker repository key
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present
- name: add nvidia-docker repository source
  get_url:
    url: https://nvidia.github.io/nvidia-docker/{{ ansible_distribution | lower }}{{ ansible_distribution_version }}/nvidia-docker.list
    dest: /etc/apt/sources.list.d/nvidia-docker.list
    owner: root
    group: root
    mode: 0644
- name: install docker and nvidia-docker
  apt:
#    name: ['docker-ce=5:18.09.6~3*', 'nvidia-docker2=2.0.3+docker18.09.6-3', docker-ce-cli, containerd.io]
    name: ['docker-ce', 'nvidia-docker2', docker-ce-cli, containerd.io]
    state: present
    update_cache: yes
  register: nvidia_docker_apt
- name: keep versions of docker and nvidia-docker
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items: [docker-ce, nvidia-docker2]
- name: reload docker configuration
  service:
    name: docker
    state: reloaded
  when: nvidia_docker_apt.changed == True
- name: add user to docker group
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes
- name: start docker
  systemd:
    name: docker.service
    state: started
    enabled: yes
  become: yes
